### ISSUE TITLE
Add GitHub Actions for testing package

### ISSUE THREAD

**Issue by x-0o0** [x-0o0/swift-guitar-chords#12]
`/🎼 패키지 테스트 -ios18`

**Comment by x-0o0** [comment]
https://github.com/cpisciotta/xcbeautify/blob/main/.github/workflows/ci.yml

파일 업로드에 대해 참고해보면 좋을 듯

**Comment by x-0o0** [comment]
### xcbeautify 적용

```yml
# xcbeautify 를 설치합니다.
- name: xcbeautify 설치
  run: |
    brew install xcbeautify
           
# GuitarChordsTests 스킴을 테스트합니다.
- name: GuitarChordsTests 테스트
  run: |
    set -o pipefail && xcodebuild [flags] | xcbeautify --renderer github-actions
           
```
